[package]
authors = ["terukiyoshida <71865394+terukiyoshida@users.noreply.github.com>"]
name = "my-blink"
edition = "2018"
version = "0.1.0"

[dependencies]
support = { path = "support" }
panic-halt = "0.2"
